name: meetai_mvp
description: "MeetArtLink MVP for AI-based image analysis"
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  google_ml_kit: ^0.19.0
  http: ^0.13.5
  image: ^3.2.0
  mediapipe: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sample_image.jpg
